import {stageVisuals,stageStory} from './stage-visuals.mjs';
import {editorial,editorialImage} from '../media.mjs';
// Growth Systems overview: three pinned states sharing the journey image-story language. The detailed
// explanation stays on the left; the photograph carries only a label, a progression and one statement.
const capabilities=[
 {eyebrow:'001 / START WITH PEOPLE',title:'Experience Design<br><em>&amp; Enablement.</em>',
  body:'Make every interaction mean more. We connect customer journeys, digital products and brand experiences around the people who use them.',
  tags:['Journey strategy','Experience design','Personalization'],href:'/growth-systems/experience-design-enablement',cta:'Build better experiences',
  image:{src:'asset:editorial/product-in-use-1600.webp',alt:'A person using a virtual reality experience in an LED installation',focus:'50% 40%'},
  label:'EXPERIENCE / 001',flow:['Discover','Connect','Return'],statement:'Every touchpoint. One experience.'},
 {eyebrow:'002 / CONNECT THE POSSIBILITIES',title:'MarTech Consulting<br><em>&amp; Enablement.</em>',
  body:'Turn a collection of platforms into a connected ecosystem. We align marketing, CRM and engagement technology so your teams can move as one.',
  tags:['Stack strategy','Implementation','Orchestration'],href:'/growth-systems/martech-consulting-enablement',cta:'Connect your technology',
  image:{src:'asset:editorial/human-screen-portrait-1600.webp',alt:'A person concentrating on a digital interaction through colourful reflections',focus:'center 32%'},
  label:'MARTECH / 002',flow:['CRM','Content','Engagement','Analytics'],statement:'Connected systems. One customer context.'},
 {eyebrow:'003 / MAKE DATA INTELLIGENCE ACTIONABLE',title:'Data Intelligence<br><em>&amp; Activation.</em>',
  body:'Bring customer and business data into focus. Turn insight into useful personalization, smarter automation and decisions your teams can act on.',
  tags:['Data foundations','Customer intelligence','Activation'],href:'/growth-systems/data-intelligence-activation',cta:'Put your data to work',
  image:{src:'asset:editorial/optical-patterns-1600.webp',alt:'Patterns becoming visible across an illuminated measuring instrument',focus:'center'},
  label:'DATA INTELLIGENCE / 003',flow:['Unify','Understand','Activate'],statement:'From signals to useful action.'}
];
export function growthJourney(){return `<section class="growth-journey" id="growth-journey" aria-label="Explore our three growth capabilities"><div class="growth-stage"><div class="journey-top"><p class="eyebrow">GROWTH, CONNECTED.</p><span class="journey-count">01 / 03</span></div><div class="capability-panels">${capabilities.map((c,i)=>`<article class="capability-panel${i===0?' is-active':''}" id="capability-${i}"><div class="capability-copy"><p class="eyebrow">${c.eyebrow}</p><h3>${c.title}</h3><p class="capability-description">${c.body}</p><ul class="inline-tags">${c.tags.map(t=>`<li>${t}</li>`).join('')}</ul><a href="${c.href}" class="text-link">${c.cta} <span>↗</span></a></div><div class="capability-visual"><img src="${c.image.src}" alt="${c.image.alt}" style="--focus:${c.image.focus}" width="1600" height="1200" loading="lazy">${stageStory(c.label,c.statement,c.flow,{sequence:true})}</div></article>`).join('')}</div><div class="journey-bottom"><div class="journey-tabs" aria-label="Growth capabilities"><button data-capability="0" aria-current="step">Experience</button><span>→</span><button data-capability="1">MarTech</button><span>→</span><button data-capability="2">Data Intelligence</button><span>→</span><a href="/ai-agents" class="growth-result">Growth <span>↗</span></a></div><div class="journey-progress"><span></span></div></div></div></section>`;}
const stories={
 experience:{eyebrow:'ONE CUSTOMER. MANY MOMENTS.',title:'Design the whole journey.',image:editorial.experience,steps:[['Discover','Web / campaign','Meet a relevant idea.','A campaign answers a real customer need and leads to a purposeful landing experience.'],['Explore','Mobile / website','Make it easy to find the right fit.','Useful content, clear navigation and responsive interfaces help people explore confidently.'],['Engage','Email / portal','Continue the conversation.','A consented interaction carries context into email, a customer portal or a saved enquiry.'],['Convert','Commerce / CRM','Make the next step feel natural.','Remove friction from checkout, booking or enquiry. Give the team the context to respond.'],['Return','Service / app','Build a reason to come back.','Customer apps and service touchpoints connect ongoing support with a more relevant next experience.']]},
 martech:{eyebrow:'FROM FRAGMENTED TO CONNECTED',title:'One journey. A system that works together.',image:{src:'asset:film-business-collaboration-poster.webp',alt:'A team coordinating work across their business systems'},steps:[['CRM','Customer context','Know who you’re speaking to.','Establish customer records, ownership and the context teams need to serve a relationship.'],['Marketing Automation','Lifecycle engagement','Make the follow-up relevant.','Connect consent, lead scoring and lifecycle triggers with campaign preparation and review.'],['CMS','Digital experience','Carry the context into content.','Align the website and content platform with the needs of the customer journey.'],['CDP','Connected customer','Bring the signals together.','Unify profiles and audiences using the identifiers and permissions appropriate to your business.'],['Analytics','Shared measurement','Give teams a common view.','Agree the events, reporting and definitions that make progress understandable.'],['Channels','One connected customer journey','Put the system to work.','CRM, campaigns, content, customer data and measurement support a coordinated experience.']]},
 data:{eyebrow:'FROM SIGNALS TO USEFUL ACTION',title:'Make customer intelligence work.',image:{name:'signals-research',alt:'A researcher carefully studying a sample through precision equipment'},steps:[['Signals','Web / app / CRM','Start with the evidence.','Map customer interactions, transactions and campaign signals, with consent and ownership in context.'],['Unified Customer','Identity / CDP','Connect a reliable profile.','Resolve identities and unify the data needed for the use case. Make gaps and quality issues visible.'],['Understanding','Analytics / insight','Find a useful pattern.','Review customer behavior, lifecycle context and funnel performance to understand where to act.'],['Audience','Segmentation','Create a relevant audience.','Translate insight into behavioral segments, lifecycle groups or real-time audiences where appropriate.'],['Action','CRM / personalization','Activate with purpose.','Bring the audience into CRM, a marketing workflow or a personalized experience, within agreed permissions.'],['Measurement','Reporting / learning','Learn what happened next.','Connect response, journey and campaign measurement to the original question. Improve the next action.']]},
 agents:{eyebrow:'INTELLIGENCE, WITH ACCOUNTABILITY',title:'Useful action. Clear human control.',image:{name:'automation-laboratory',alt:'Precision automation equipment operating in a real laboratory'},steps:[['Understand','Knowledge / request','Understand the work and its context.','Connect the request with the right company knowledge, customer context and process rules.'],['Reason','Plan / evaluate','Prepare an appropriate next step.','Compare available information, identify uncertainty and choose an action within the agreed boundaries.'],['Act','Tools / systems','Move the work forward.','Prepare an output or use an approved connection to CRM, APIs, databases or an internal application.'],['Human Control','Review / approval','Keep people at critical decisions.','Route sensitive actions and uncertain cases to the right person. Make context and proposed changes clear.'],['Outcome','Measure / improve','Evaluate usefulness, then improve.','Review results, exceptions and handoffs. Refine the knowledge, workflow and evaluation with your team.']]}
};
export function signatureStory(kind){const s=stories[kind];return `<section class="signature-section section-pad signature-${kind} ${['experience','martech','data','agents'].includes(kind)?'refined-journey':''}"><div class="section-lead"><p class="eyebrow">${s.eyebrow}</p><div><h2>${s.title}</h2><p>${kind==='martech'?'Explore how each platform becomes part of the same customer journey.':kind==='agents'?'Understand the work. Reason within boundaries. Act through approved systems. Keep people in control. Learn from the outcome.':'Follow a practical journey from context to a useful next step.'}</p></div></div><div class="signature-story" data-signature="${kind}"><div class="signature-photo">${stageVisuals(kind)||editorialImage(s.image)}<div class="signature-photo-caption"><span class="signature-counter">01 / ${String(s.steps.length).padStart(2,'0')}</span><span>${kind==='experience'?'EVERY TOUCHPOINT. ONE EXPERIENCE.':kind==='martech'?'TECHNOLOGY, CONNECTED TO PEOPLE.':kind==='data'?'EVIDENCE. UNDERSTANDING. ACTION.':'HUMAN + MACHINE. BETTER TOGETHER.'}</span></div></div><div class="signature-content"><ol class="signature-steps">${s.steps.map(([name],i)=>`<li><button type="button" id="${kind}-step-${i}" aria-controls="${kind}-panel-${i}" data-signature-step="${i}" ${i===0?'aria-current="step"':''}><span>0${i+1}</span>${name}</button></li>`).join('')}</ol><div class="signature-panels">${s.steps.map(([name,channel,title,body],i)=>`<div class="signature-panel" id="${kind}-panel-${i}" role="region" aria-labelledby="${kind}-step-${i}" ${i?'hidden':''}><p class="eyebrow">${channel}</p><h3>${title}</h3><p>${body}</p></div>`).join('')}</div><div class="signature-bottom"><span>ILLUSTRATIVE JOURNEY</span><button type="button" class="signature-play" aria-label="Pause journey">Pause journey</button></div></div></div></section>`;}
export const capabilityContent = [
 [['Websites that serve a purpose.','Corporate and B2B websites, commerce and campaign experiences, and customer portals. We connect content, information architecture and development to the action your audience needs to take.'],['Digital products people can use.','Custom web applications, SaaS experiences, membership and booking platforms, business portals and digital tools. We shape the workflows, design the interface and build the experience.'],['Useful, wherever the work happens.','iOS and Android experiences, customer apps, business applications and field tools. Designed around real tasks, device context and the connections people need to keep moving.'],['One journey across touchpoints.','Journey mapping, touchpoint strategy, funnel design and conversion journeys. We connect web, mobile, email, CRM and service into an experience with a clear next step.'],['Good design starts with understanding.','User research, information architecture, interaction design, interface design and prototyping. Reusable design systems connect a coherent customer experience with a practical delivery process.'],['Keep making the experience better.','Personalization, conversion optimization, testing and behavior-led improvements. We use evidence to identify friction and refine the experience around your customers.']],
 [['Know what you have. Define what you need.','Current-state audits, capability assessments, stack rationalization, platform selection and roadmaps. Make technology decisions with a clear view of your business priorities and operating reality.'],['Architecture around the customer journey.','MarTech and CRM architecture, integration planning and journey architecture. Define how data, content, permissions and workflows move between systems before configuration begins.'],['Implement the connected foundation.','CRM, marketing automation, CDP, CMS, analytics, APIs and platform integrations. We turn the architecture into usable connections and workflows your teams can operate.'],['Make engagement work across the lifecycle.','Lifecycle journeys, lead nurturing and scoring, segmentation, triggers and campaign workflows. Bring customer context into the next interaction with clear review and ownership.'],['Support the work of modern marketing.','Campaign setup, execution, optimization, testing and reporting. We help teams operate the platforms consistently and improve the workflows that support each release.'],['Modernize without losing the context.','Platform, data and journey migration, with process modernization alongside the technical work. Plan the transition around data quality, continuity and the people who use the system.'],['Make adoption part of delivery.','Training, governance, operating models and ongoing support or managed enablement. Clear ownership and practical documentation help teams keep improving after launch.']],
 [['Build a trusted customer foundation.','Data unification, customer profiles, identity resolution and CDP strategy. Start with useful sources, dependable identifiers and clear ownership of the customer context.'],['Turn understanding into an audience.','Behavioral segments, lifecycle audiences, real-time audiences and activation. Define who should receive an experience and why, within the permissions your business has established.'],['Make performance understandable.','Dashboards, marketing reporting, customer analytics, campaign performance and business intelligence. Give teams useful views of the questions they need to answer.'],['Measure the journey that matters.','Marketing measurement, funnel performance and journey measurement, with attribution where applicable. Agree the definitions, limitations and decisions each measure should support.'],['Put intelligence into the experience.','CRM and marketing automation activation, personalization and trigger-based engagement. Connect a relevant audience or insight to a useful action in the systems teams already use.'],['Make the data ready for real work.','Data quality, consent, governance and operational readiness. Establish the checks, responsibilities and working practices that keep customer data useful.'],['Find the next useful pattern.','Predictive insight, pattern identification, next-best-action thinking and AI-assisted analysis where applicable. Match the method to the available evidence and keep interpretation grounded in business context.']]
];
export function capabilityChapters(index){return `<section class="capability-editorial section-pad"><div><p class="eyebrow">FROM STRATEGY TO IMPLEMENTATION</p><h2>${['Experiences.<br>Designed and built.','Technology.<br>Enabled for your team.','Data intelligence.<br>Ready for action.'][index]}</h2></div><div class="capability-chapters">${capabilityContent[index].map(([h,p],i)=>`<article class="reveal"><span>0${i+1}</span><div><h3>${h}</h3><p>${p}</p></div></article>`).join('')}</div></section>`;}
