import {socialIcon} from './socials.mjs';
import {heroMedia,editorialImage} from '../media.mjs';
import {productDemo,projectVisual} from './showcase.mjs';
import {site,services} from '../site.mjs';
export const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const link = (href,label,classes='text-link') => `<a class="${classes}" href="${esc(href)}">${label}<span aria-hidden="true">↗</span></a>`;
export const logo = () => `<a class="brand asset-brand" href="/" aria-label="InnooRyze home"><img src="${site.logo}" alt="InnooRyze" width="894" height="207"></a>`;
export function header(path){const nav=[['AI Agents','/ai-agents'],['Products','/products'],['Work','/work'],['Ideas Hub','/ideas-hub'],['About','/about'],['Contact','/contact']];return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header ${path==='/'?'':'inner-header'}" id="header">${logo()}<nav class="desktop-nav" aria-label="Main navigation"><div class="mega-root"><a href="/growth-systems" ${path.startsWith('/growth-systems')?'aria-current="page"':''}>Growth Systems</a><button class="mega-toggle" aria-expanded="false" aria-controls="growth-menu" aria-label="Explore Growth Systems pages"><span class="nav-chevron" aria-hidden="true"></span></button><div class="mega-menu" id="growth-menu" hidden><div><span class="eyebrow">ONE CONNECTED FOUNDATION</span><p>Experience + Technology<br>+ Intelligence = Growth</p>${link('/growth-systems','Explore Growth Systems')}</div><div>${services.map(s=>`<a href="/growth-systems/${s.slug}"><span>${s.number}</span><strong>${s.name}</strong><span>↗</span></a>`).join('')}</div></div></div>${nav.map(([label,href])=>`<a href="${href}" ${path===href||path.startsWith(href+'/')?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${link('/contact','Let’s Talk','talk-link')}<button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" aria-label="Open menu"><span></span><span></span></button></header><nav class="mobile-nav" id="mobile-nav" aria-label="Mobile navigation" hidden><a href="/growth-systems">Growth Systems</a><div class="mobile-subnav">${services.map(s=>`<a href="/growth-systems/${s.slug}">${s.name}</a>`).join('')}</div>${nav.map(([label,href])=>`<a href="${href}">${label}</a>`).join('')}</nav>`;}
export function closing(){return `<section class="contact section-pad"><div class="contact-top"><p class="eyebrow">BUILD THE FOUNDATION. ADD THE INTELLIGENCE.</p><span class="contact-plus" aria-hidden="true">+</span></div><h2 class="reveal">Ready to <span>Ryze?</span></h2><div class="contact-bottom"><p>Let’s build what moves<br>your business forward.</p>${link('/contact','Start a Conversation','contact-cta')}</div><div class="contact-details"><a href="mailto:${site.email}">${site.email}</a></div></section>`;}
export function footer(){return `<footer class="site-footer"><div class="footer-top">${logo()}<p>Growth Systems.<br>AI Agents &amp; Automation.</p><div class="footer-links"><a href="/products">Products</a><a href="/work">Work</a><a href="/ideas-hub">Ideas Hub</a><a href="/platforms">Platforms</a></div><div class="footer-links"><a href="/about">About</a><a href="/contact">Contact</a><button class="back-top">Back to top ↑</button></div></div><div class="footer-socials">${Object.entries(site.socials).filter(([,url])=>url).map(([name,url])=>`<a href="${esc(url)}" aria-label="InnooRyze on ${name==='x'?'X':name==='linkedin'?'LinkedIn':'Instagram'}" target="_blank" rel="noopener noreferrer">${socialIcon(name)}</a>`).join('')}</div><div class="footer-bottom"><span>© ${new Date().getFullYear()} InnooRyze</span><span>${site.tagline}</span><a href="/credits">Visual credits</a>${Object.entries(site.policies).filter(([,url])=>url).map(([name,url])=>`<a href="${esc(url)}">${{privacy:'Privacy Policy',cookies:'Cookie Policy',terms:'Terms'}[name]}</a>`).join('')}</div></footer>`;}
export function layout({path,title,description,body,theme='',schema=[],closingCta=true,type='website',indexable=true,socialImage:providedSocialImage}){
 const canonical = new URL(path,site.url).href;
 const socialImage=new URL(providedSocialImage||site.logo,site.url).href;
 const graph=[{'@type':'Organization','@id':`${site.url}/#organization`,name:site.name,url:site.url,logo:new URL(site.logo,site.url).href,email:site.email,sameAs:Object.values(site.socials).filter(Boolean)},{'@type':'WebSite','@id':`${site.url}/#website`,name:site.name,url:site.url},{'@type':'WebPage','@id':canonical,url:canonical,name:title,description,isPartOf:{'@id':`${site.url}/#website`}},...schema];
 const parent=path.split('/').slice(0,-1).join('/');
 const parentNames={'/growth-systems':'Growth Systems','/products':'Products','/work':'Our Work','/ideas-hub':'Ideas Hub','/platforms':'Platform Expertise'};
 if(path!=='/')graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:site.url},...(parentNames[parent]?[{'@type':'ListItem',position:2,name:parentNames[parent],item:new URL(parent,site.url).href}]:[]),{'@type':'ListItem',position:parentNames[parent]?3:2,name:title.split(' | ')[0],item:canonical}]});
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="analytics-id" content="${esc(site.analyticsId)}"><meta name="theme-color" content="#11191b"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${site.indexable&&indexable?'index,follow':'noindex,follow'}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:site_name" content="InnooRyze"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(socialImage)}"><meta property="og:image:alt" content="${esc(title)}"><meta name="twitter:image" content="${esc(socialImage)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="icon" type="image/svg+xml" href="${site.symbol}"><link rel="stylesheet" href="/style.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c')}</script><script type="module" src="/app.js"></script></head><body class="${esc(theme)}" data-page="${esc(path)}">${header(path)}<main id="main">${body}${closingCta?closing():''}</main>${footer()}<noscript><style>.story-scroll{height:auto}.story-stage{position:static;height:auto}.story-scene{position:relative;opacity:1;visibility:visible;transform:none;padding:60px 0}.growth-journey{height:auto}.growth-stage{position:static;height:auto}.capability-panel{position:relative;opacity:1;visibility:visible;transform:none;margin:50px 0;min-height:500px}.journey-bottom,.film-controls,.menu-toggle,.agent-playground,.contact-form,.filter-bar{display:none}</style></noscript></body></html>`;
}
export const pageHero=({eyebrow,title,description,extra='',className='',media:providedMedia})=>{const media=providedMedia||heroMedia(className);return `<section class="page-hero section-pad ${className} ${media?'has-editorial':''} ${media&&!className.includes('agents-page-hero')?'canvas-hero':''}"><p class="eyebrow reveal">${eyebrow}</p><h1 class="reveal">${title}</h1><div class="page-hero-bottom"><p class="reveal">${description}</p>${extra}</div>${media?`<figure class="hero-art">${editorialImage(media,{eager:true,sizes:'100vw'})}<figcaption>${media.label}</figcaption></figure>`:''}</section>`;};
export const articlePreview = a => `<article class="editorial-item reveal"><a href="/ideas-hub/${a.slug}">${editorialImage(a.image)}<div class="editorial-overlay"><div class="editorial-meta"><span>${a.category}</span><span>${a.type}</span></div><h3>${a.title}</h3><p>${a.summary}</p><div class="editorial-bottom"><span>Read Article · ${a.readTime}</span><span aria-hidden="true">↗</span></div></div></a></article>`;
export const workFeature = w => `<a class="real-work-feature reveal project-${w.slug}" href="/work/${w.route||w.slug}"><div class="project-visual">${projectVisual(w)}</div><div class="real-work-caption"><div><span class="eyebrow">${w.type} / ${w.name}${w.status?' / '+w.status:''}</span><h3>${w.title}</h3></div><span class="project-round" aria-hidden="true">↗</span></div></a>`;
export function leadDesk(){return productDemo('lead');}
