import {editorialImage} from '../media.mjs';
import {site,products,platforms} from '../site.mjs';
import {arrowUpRight} from './icons.mjs';
export function productDemo(kind='lead'){
 const lead=kind==='lead';
 const steps=lead?['Conversation','Qualification','Lead profile','CRM','Sales action']:['Business context','Capability review','Maturity profile','Priorities','Next steps'];
 const scenes=lead?[
  ['A useful first answer','Visitor','Can you support a rollout across three markets?','LeadRyze AI','Yes. Your product knowledge helps me explain the right options. Which teams will use the solution?'],
  ['Understand the opportunity','Visitor','Sales and marketing. We’re planning for next quarter.','LeadRyze AI','Thanks. What does your current setup look like, and who should we involve in the next conversation?'],
  ['Context becomes a lead','Qualified enquiry','Alex Morgan · Northstar Studio','PROFILE PREPARED','Three markets · Sales & marketing · Next-quarter rollout. Business context and conversation captured.'],
  ['Connected with your CRM','CRM workspace','New lead · Alex Morgan','READY FOR YOUR TEAM','Northstar Studio · Exploring regional expansion. Conversation context attached. Owner: Sales team.'],
  ['A clear next step','Sales action','Discovery meeting requested','HUMAN HANDOFF','Your team has the context to follow up. Meeting preferences are ready for confirmation.']
 ]:[
  ['Start with your business','Assessment','Choose the context that fits your organization.','BUSINESS MODEL','B2B or B2C. Shape the assessment around how you go to market.'],
  ['Explore the foundations','Capability review','Experience. Technology. Data. People.','STRUCTURED QUESTIONS','Review your customer journeys, marketing stack and operating capabilities.'],
  ['See the whole picture','Maturity profile','Understand your current foundations.','ILLUSTRATIVE PROFILE','Bring strengths and development areas into one shared perspective.'],
  ['Find the next opportunity','Priorities','Connect customer context across teams.','A FOCUSED START','Use the assessment to identify where closer alignment could support your marketing.'],
  ['Move from insight to action','Next steps','Start a more informed conversation.','GROW FROM HERE','Explore your findings with the people who own the experience, platforms and data.']
 ];
 return `<div class="product-demo" data-demo="${kind}" aria-label="${lead?'LeadRyze AI':'IMMA'} illustrative demonstration"><div class="demo-top"><strong>${lead?'LeadRyze <em>AI</em>':'IMMA'}</strong><span>ILLUSTRATIVE DEMO</span></div><div class="demo-scenes">${scenes.map(([title,from,message,by,response],i)=>`<div class="demo-scene${i===0?' is-active':''}" ${i?'hidden':''}><div class="demo-caption"><span>0${i+1} / 05</span><h4>${title}</h4></div><div class="demo-bubble"><span>${from}</span><p>${message}</p></div><div class="demo-reply"><span class="demo-brand" aria-hidden="true">${arrowUpRight()}</span><div><span>${by}</span><p>${response}</p></div></div>${i===2?`<div class="demo-profile"><span>${lead?'Company context':'Experience'}</span><span>${lead?'Buyer intent':'Technology'}</span><span>${lead?'Next step':'Intelligence'}</span></div>`:''}</div>`).join('')}</div><div class="demo-steps" aria-label="Demonstration steps">${steps.map((s,i)=>`<button type="button" data-demo-step="${i}" aria-label="Show ${s}" ${i===0?'aria-current="step"':''}><span>0${i+1}</span>${s}</button>`).join('')}</div><div class="demo-footer"><span>${lead?'Fictional buyer and company. Your CRM, your process.':'Illustrative journey. Explore the live assessment.'}</span><button type="button" class="demo-play" aria-label="Pause demonstration">Pause</button></div></div>`;
}
export function productShowcase(){return `<div class="product-showcase">${products.slice(0,2).map((p,i)=>`<article class="showcase-product${i===0?' is-open':''}" data-product="${p.slug}"><h3><button type="button" class="showcase-toggle" aria-expanded="${i===0}" aria-controls="showcase-${p.slug}"><span class="showcase-number">0${i+1}</span><span>${p.name}</span><small>${i?'Marketing clarity. A stronger starting point.':'An intelligent front desk for growth.'}</small><span class="showcase-sign" aria-hidden="true">${i?'＋':'−'}</span></button></h3><div class="showcase-fold" id="showcase-${p.slug}" ${i?'inert':''}><div><div class="showcase-layout"><div class="flagship-copy"><div class="product-kicker"><span>${i?'MARKETING MATURITY ASSESSMENT':'FLAGSHIP PRODUCT'}</span><span class="availability">Available</span></div><h4>${i?'Know where you stand.<br><em>Grow from there.</em>':'Your next opportunity<br>starts with a <em>better conversation.</em>'}</h4><p>${p.description}</p><a class="text-link" href="${p.href}">${i?'Explore IMMA':'Meet your AI lead desk'} <span aria-hidden="true">${arrowUpRight()}</span></a>${i?`<a class="showcase-live" href="${site.assessmentUrl}" target="_blank" rel="noopener noreferrer">Try the live assessment ${arrowUpRight()}</a>`:''}</div>${productDemo(i?'imma':'lead')}</div></div></div></article>`).join('')}</div>`;}
export function projectVisual(w){return w.campaign?`${editorialImage(w.campaign,{classes:'project-campaign-image'})}<div class="project-campaign-caption"><span>${w.status||'INNOORYZE / SELECTED WORK'}</span><strong>${w.name}</strong></div>`:`<img class="project-campaign-image" src="${w.image}" alt="${w.alt}" width="1440" height="900" loading="lazy">`;}
export function workCarousel(items){return `<div class="work-carousel" role="region" aria-roledescription="carousel" aria-label="Selected InnooRyze work"><div class="work-track" tabindex="0" aria-label="Projects. Use left and right arrow keys to explore.">${items.map((w,i)=>`<div class="work-slide project-${w.slug}" role="group" aria-roledescription="slide" aria-label="${i+1} of ${items.length}: ${w.name}"><a href="/work/${w.route||w.slug}" class="project-visual">${projectVisual(w)}<span class="project-peek" aria-hidden="true">Explore ${arrowUpRight()}</span></a><div class="project-info"><div><p class="eyebrow">${w.type}</p><h3><a href="/work/${w.route||w.slug}">${w.name} <span aria-hidden="true">${arrowUpRight()}</span></a></h3></div><p>${w.description}</p>${w.status?`<span class="project-status">${w.status}</span>`:''}<a class="project-case-link" href="/work/${w.route||w.slug}">View case study <span aria-hidden="true">${arrowUpRight()}</span></a></div></div>`).join('')}</div><div class="carousel-controls"><span class="carousel-count" aria-live="polite">01 / ${String(items.length).padStart(2,'0')}</span><div class="carousel-progress" aria-hidden="true"><span></span></div><button type="button" data-carousel-prev aria-label="Previous project">←</button><button type="button" data-carousel-next aria-label="Next project">→</button></div></div>`;}
export {homePlatformBlocks as platformBlocks} from './platforms.mjs';
