import {policies,policyPaths} from './content/policies.mjs';
import {editorial} from './media.mjs';
export const site = {
  name: 'InnooRyze',
  url: process.env.SITE_URL || 'https://innooryze.com',
  indexable: process.env.SITE_INDEXABLE !== 'false',
  email: 'enquiry@innooryze.com',
  logo: '/assets/brand/brand-logo.png',
  symbol: '/assets/brand/brand-symbol.svg',
  enquiryEndpoint: process.env.ENQUIRY_ENDPOINT || '',
  assessmentUrl: 'https://assessment.innooryze.com/',
  tagline: 'Innovate. Integrate. Elevate.',
  socials: {linkedin:process.env.SOCIAL_LINKEDIN_URL || 'https://in.linkedin.com/company/innooryze',x:process.env.SOCIAL_X_URL || 'https://x.com/innooryze',instagram:process.env.SOCIAL_INSTAGRAM_URL || 'https://www.instagram.com/innooryze'},
  policies: {privacy:process.env.PRIVACY_POLICY_URL || (policies.some(p=>p.key==='privacy')?policyPaths.privacy:''),cookies:process.env.COOKIE_POLICY_URL || (policies.some(p=>p.key==='cookies')?policyPaths.cookies:''),terms:process.env.TERMS_URL || (policies.some(p=>p.key==='terms')?policyPaths.terms:'')},
  analyticsId: process.env.ANALYTICS_ID || ''
};
export const services = [
  {slug:'experience-design-enablement', name:'Experience Design & Enablement', short:'Experience', number:'001', phrase:'Experiences that bring people closer.', description:'Design and build connected digital experiences, customer journeys, websites, applications and personalized content around the people who use them.', eyebrow:'START WITH PEOPLE', areas:['Customer journey strategy','Websites & digital applications','UX, UI & content experiences','Personalization & optimization'], output:'A clearer journey, a purposeful experience and the design and engineering to bring it to life.', link:'Technology makes the experience possible. Intelligence makes it more relevant.', adjacent:1},
  {slug:'martech-consulting-enablement', name:'MarTech Consulting & Enablement', short:'Technology', number:'002', phrase:'Make your technology work together.', description:'Assess, architect, implement, integrate and improve the platforms behind modern marketing, CRM and customer engagement.', eyebrow:'CONNECT THE SYSTEM', areas:['MarTech assessment & architecture','Platform implementation & integration','CRM & marketing automation','Campaigns, journeys & optimization'], output:'A connected marketing ecosystem with clear ownership, useful workflows and platforms your teams can put to work.', link:'Experience gives technology its purpose. Intelligence guides what happens next.', adjacent:2},
  {slug:'data-intelligence-activation', name:'Data Intelligence & Activation', short:'Intelligence', number:'003', phrase:'From customer data to a useful next step.', description:'Unify, understand and activate customer and business data through segmentation, analytics, CDP, measurement and actionable intelligence.', eyebrow:'TURN SIGNALS INTO ACTION', areas:['Customer data & CDP consulting','Data quality & identity','Analytics, measurement & segmentation','Personalization & activation'], output:'Trusted customer context, a shared way to measure progress and intelligence that informs real decisions.', link:'Technology connects the data. Experience is where its value becomes visible.', adjacent:0}
];
export const products = [
  {slug:'leadryze-ai',name:'LeadRyze AI',category:'FLAGSHIP AI LEAD DESK',status:'Available',description:'From the first buyer question to a qualified conversation. An AI lead desk that understands your business and helps opportunities move forward.',href:'/products/leadryze-ai'},
  {slug:'imma',name:'IMMA',category:'INTELLIGENT MARKETING MATURITY ASSESSMENT',status:'Available',description:'Find the gaps across your marketing stack, customer journeys, data and capabilities. Get a clearer starting point for what comes next.',href:'/products/imma'},
  {slug:'campaign-automation',name:'Campaign automation',category:'PRODUCT ROADMAP',status:'In development',description:'End-to-end campaign workflows, from planning and preparation to coordinated execution.'},
  {slug:'brand-social-content',name:'Brand & social content',category:'PRODUCT ROADMAP',status:'In development',description:'AI-supported content workflows that connect brand knowledge, creative development and publishing.'},
  {slug:'performance-intelligence',name:'Performance intelligence',category:'PRODUCT ROADMAP',status:'In development',description:'Performance signals and next-best-action insights that help teams decide where to focus.'}
];
export const articles = [
  {slug:'choosing-the-right-cdp-for-your-growth-stage',title:'Choosing the right CDP for your growth stage.',category:'Data & Intelligence',type:'Guide',readTime:'3 min read',summary:'Start with the decisions and customer experiences you need to improve. Then choose the data foundation to support them.',sections:[
    ['Start with a use case, not a platform.','A customer data platform should solve a specific problem. That might be fragmented customer profiles, inconsistent audiences or the difficulty of making a relevant next interaction possible. Write down the first use case before building a requirements list.'],
    ['Understand what your data can support.','Map your sources, identifiers, consent and ownership. Establish where data is collected, how it stays accurate and which teams can use it. A platform cannot replace those decisions.'],
    ['Connect the selection to your growth stage.','Look at the channels you operate, the scale of your data and the people who will maintain the system. Match the implementation to what the business can adopt. Leave room to grow without making the first use case unnecessarily complex.'],
    ['Design for activation.','Decide where an audience or insight must go next: a website, a CRM, a campaign or an analytics workflow. Assess integration and operating requirements alongside the platform features.'],
    ['Give the first use case a clear owner.','Agree how you will judge usefulness, who maintains the data and who acts on the result. The goal is a working customer experience with a sustainable operating model.']
  ]},
  {slug:'why-ai-needs-human-centered-strategy',title:'Why AI needs human-centered strategy.',category:'AI & Agents',type:'Perspective',readTime:'3 min read',summary:'Useful AI starts with an understanding of people, their context and the work that needs to get done.',sections:[
    ['Define the work before choosing the AI.','Begin with a customer need or a business process. Describe what a good outcome looks like, what information is necessary and which decisions should remain with a person. That gives the technology a useful purpose.'],
    ['Make context part of the experience.','An answer is only helpful when it fits the situation. Product knowledge, customer preferences and process rules should inform how an agent responds. Missing or uncertain information should lead to a clear question or a human handoff.'],
    ['Give people control.','Decide which actions an agent can prepare, which it may execute and which require approval. Make those boundaries understandable to the people using and operating the system.'],
    ['Evaluate more than speed.','Review whether the agent understood the request, used the right context and prepared an appropriate next step. A faster answer is not necessarily a better experience.'],
    ['Learn from real interactions.','Start with a bounded workflow. Observe where customers or teams need help, improve the knowledge and refine the handoffs. Human understanding remains an ongoing part of the system.']
  ]},
  {slug:'3-common-mistakes-in-martech-implementation',title:'3 common mistakes in MarTech implementation.',category:'MarTech',type:'Article',readTime:'3 min read',summary:'The platform is only part of the work. Alignment, data and adoption determine whether the system becomes useful.',sections:[
    ['1. Starting with features instead of the journey.','A long feature list can hide a lack of agreement about what the business needs. Define the customer journey, the team workflow and the first measurable use case before configuring the platform.'],
    ['2. Leaving data and integration until later.','Identify the systems of record, the customer identifiers, the consent requirements and the owners of each connection early. Integration decisions affect the experience your teams can actually deliver.'],
    ['3. Treating launch as the finish line.','People need a clear way to operate the system. Plan training, ownership, documentation and a rhythm for improvement. Make it easy to understand what is working and where a workflow needs attention.'],
    ['Build the operating model alongside the technology.','Connect customer experience, platform delivery and data from the start. Give the first use case a clear owner, validate the full journey and use what you learn to guide the next release.']
  ]}
];
articles.forEach((a,i)=>{a.published='2026-09-12';a.updated='2026-09-13';a.readTime=Math.max(1,Math.ceil(a.sections.map(x=>x.join(' ')).join(' ').split(/\s+/).length/200))+' min read';a.image=[editorial.data,editorial.martech,editorial.about][i];});
export const work = [
 {slug:'dynalektric',name:'Dynalektric',title:'Engineering expertise. A clearer digital experience.',type:'Experience Design & Enablement',categories:['Website Experience'],image:'asset:dynalektric-screen.webp',alt:'The live Dynalektric website with its industrial engineering and manufacturing homepage',industry:'Industrial electrical manufacturing',description:'Website strategy, UX, design and development for an industrial electrical manufacturer.',challenge:'Present industrial engineering capabilities through a clear, useful digital experience.',approach:'Website strategy, user experience, design and development.',built:'A company website connecting manufacturing capabilities, products, applications and enquiry journeys.',technology:'Experience strategy, information architecture, UX, interface design and web development.',outcome:'The website is live.',url:'https://dynalektric.com/',related:0},
 {slug:'treffer-technologies',name:'Treffer Technologies',title:'Connecting the platforms behind customer engagement.',type:'MarTech / CRM Enablement',categories:['MarTech','CRM'],industry:'Technology',description:'CRM and marketing technology enablement.',approach:'CRM and MarTech enablement for Treffer Technologies.',technology:'CRM and marketing technology enablement.',related:1},
 {slug:'max-seal',route:'maxseal',name:'Max-Seal',title:'A digital experience for industrial flow control.',type:'Experience Design & Enablement',categories:['Website Experience'],status:'In Progress',image:'asset:max-seal-screen.webp',alt:'The current Max-Seal website showing its industrial valve application explorer, with the build in progress',industry:'Industrial valves and flow control',description:'A new digital experience for Max-Seal. The build is currently in progress.',approach:'Experience design and development for the current website build.',built:'A digital experience in development, presenting industrial valve products and applications.',technology:'Experience Design & Enablement.',url:'https://max-seal.vercel.app/',related:0},
{slug:'imma',title:'A clearer starting point for marketing growth.',name:'IMMA',type:'InnooRyze product',categories:['Website Experience','Data','AI'],image:'asset:imma-screen.png',alt:'The live IMMA assessment showing business-model selection for B2B and B2C organizations',description:'An intelligent marketing maturity assessment that helps businesses explore the strength of their marketing foundations.',challenge:'Make it easier for decision-makers to identify where their marketing foundations need attention.',approach:'Organize the assessment around business context, marketing capabilities, customer journeys and data.',built:'A guided web assessment with distinct B2B and B2C starting points and a structured progression through marketing maturity.',technology:'A browser-based assessment experience. It can be explored directly through the live IMMA product.',outcome:'A live, accessible starting point for understanding marketing maturity. Quantified business outcomes have not been published.'}];
work.forEach(w=>{w.campaign=w.slug==='dynalektric'?{src:'asset:dynalektric-project.webp',alt:'A technician assembling electrical components in the Dynalektric film'}:w.slug==='max-seal'?{src:'asset:max-seal-project.webp',alt:'An industrial valve assembly from the Max-Seal product film'}:w.slug==='treffer-technologies'?{name:'optical-patterns',alt:'Illustrative optical patterns across a measuring instrument, representing connected intelligence'}:null;});
export const platforms = [
  {name:'Salesforce',slug:'salesforce',image:'/assets/platforms/salesforce-logo.svg',group:'CRM & customer engagement'},
  {name:'Adobe',slug:'adobe',image:'/assets/platforms/adobe-logo.png',group:'Digital experience & marketing'},
  {name:'Braze',slug:'braze',image:'/assets/platforms/braze-logo.svg',group:'Customer engagement'},
  {name:'Segment',slug:'segment',image:'/assets/platforms/segment-logo.svg',group:'Customer data'}
];
export const interests = ['Growth Systems','Experience Design & Enablement','MarTech Consulting & Enablement','Data Intelligence & Activation','AI Agents & Automation','LeadRyze AI','LeadRyze CRM','IMMA','Partnership','Other'];
